name: delete branch on close pr(api)

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        with:
          script: |
            const octokit = new Octokit({
              auth: ${{secrets.GITHUB_TOKEN}}
              numbers: ${{github.event.pull_request.number}}
              })

                await octokit.request('DELETE /repos/saketksinha/Simple_Telegram_Chatbot/git/refs/numbers, {
                owner: 'saketksinha',
                repo: 'Simple_Telegram_Chatbot',
                ref: 'head',
                headers: {
                'X-GitHub-Api-Version': '2022-11-28'
                }
            })
