name: delete branch on close pr
on:
  pull_request:
    types: [closed]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  delete-branch:
    runs-on: ubuntu-latest
    steps:
     - name: Delete closed PR branch
       uses: ./.github/action
       with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        numbers: ${{github.event.pull_request.number}}
