name: delete branch on close pr(api)

on:
  pull_request:
    types: [closed, labeled]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
        
      - name: This will send branch delete request
        run: |
          if: "contains(github.event.pull_request.labels.*.name, 'status: needs-attention')"
          curl -s -X DELETE -u username:${{secrets.GITHUB_TOKEN}} https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ github.head_ref }}
        
