name: Delete Unmerged Closed Branches

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Delete Unmerged Closed Branches
      env:
        PAT_TOKEN: ${{ secrets.SECRET_TOKEN }}
      run: |
        git checkout main # Change 'main' to your default branch
        git fetch --prune
        git branch --no-color --merged | grep -v '^\*' | xargs -I {} git branch -d {}
        git fetch --prune origin "+refs/pull/*/merge:refs/remotes/origin/pr/*"
        git for-each-ref --format='%(refname:default)' refs/remotes/origin/pr/* | xargs -I {} sh -c 'git push --delete origin {}:'
