name: Mark stale pull requests

on:
 schedule:
    - cron: '0 0 * * *' # run daily at midnight UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v8
      with:
        days-before-stale: 1
        days-before-close: 1
        delete-branch: 1
        stale-pr-label: 'no-pr-activity'
        stale-pr-message: 'This pr is stale because it has been open for 30 days with no activity.'
        close-pr-message: "This pr was closed because it has been inactive for 14 days since being marked as stale."
      
