name: Delete Closed Branches with Label

on:
  pull_request:
    types: [closed, labeled]

jobs:
 delete-branch-if-not-labeled:
     runs-on: ubuntu-latest
     if: |
       github.event.action == 'closed' &&
       github.event.label.name == 'bug'
     steps:
      - name: This will send branch delete request
        run: |
            curl -s -X DELETE -u username:${{secrets.GITHUB_TOKEN}} https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ github.head_ref }}
            
 donot-delete-branch-if-labeled:
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'labeled' &&
      github.event.label.name == 'bug'
    steps:
      - name: Skipped
        run: echo "Branch will not be deleted because it's labeled with 'bug'"
        
  
