on:
  pull_request:
    types: [closed]
jobs:
 delete-branch:
   runs-on: ubuntu-latest
   steps:
    - name: delete branch
      env:
       GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
       delete_closed_pr: true
