name: delete branch on close pr(api)

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: REST API with curl
        if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'help wanted')
        run: |
          curl -s -X DELETE -u username:${{secrets.GITHUB_TOKEN}} https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ github.head_ref }}
        
